---

- name: Install configs
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/git/gitlab.com/mslt/configs/i3"
    dest: "{{ lookup('env', 'HOME') }}/.config/i3"
    state: link
    force: True
  become: False
  notify: Restart i3wm