---

- name: Install ohmyzsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: "{{ lookup('env', 'HOME') }}/.ohmyzsh"
    state: present
  become: False

- name: Install powerlevel9k
  ansible.builtin.git:
    repo: https://github.com/powerlevel9k/powerlevel9k
    dest: "{{ lookup('env', 'HOME') }}/.ohmyzsh/custom/themes/powerlevel9k"
    state: present
  become: False

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ lookup('env', 'HOME') }}/.ohmyzsh/custom/themes/powerlevel10k"
    depth: 1
    state: present
  become: False

- name: Link configs
  ansible.builtin.file:
    state: link
    src: "{{ lookup('env', 'HOME') }}/git/gitlab.com/mslt/configs/zsh/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.{{ item }}"
  become: False
  loop:
    - zshrc
    - aliases
    - p10k.zsh