# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export PATH="$PATH:/$HOME/.local/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$HOME/bin"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs docker_machine status root_indicator background_jobs)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(command_execution_time context virtualenv dir)
DEFAULT_USER=mslt
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  fzf
  gitignore
)

# if [[ ! ${TMUX} ]] ; then
#   tmux attach || tmux
# fi

source $ZSH/oh-my-zsh.sh

if [[ -e /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] ; then
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
elif [[ -e /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] ; then
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
else
  if [[ ! -e $HOME/.zsh_suppress_warnings ]] ; then
    echo "Could not load zsh-autosuggestions from known sources"
  fi
fi

if [[ -e /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] ; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 
elif [[ -e /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] ; then
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
else
  if [[ ! -e $HOME/.zsh_suppress_warnings ]] ; then
    echo "Could not load zsh-syntax-highlighting from known sources"
  fi
fi

if [[ -e $HOME/.aliases ]] ; then
  source $HOME/.aliases
else
  if [[ ! -e $HOME/.zsh_suppress_warnings ]] ; then
    echo "Could not load aliases from known sources"
  fi
fi
  
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
complete -o nospace -C /usr/bin/terraform terraform

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/.gh-token
