syntax on
set tabstop=2
set number
set rnu
set background=dark
set t_Co=256
filetype plugin indent on
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:.
set list
set expandtab
set shiftwidth=2
set softtabstop=2
colorscheme slate
set omnifunc=syntaxcomplete#Complete


let g:ycm_global_ycm_extra_conf = '/usr/share/vim/vimfiles/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_server_python_interpreter = '/usr/sbin/python2'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

noremap <F2> gT
noremap <F3> gt
noremap <F4> :set list! <CR>
noremap <F5> :set list <CR>

" Disable pleb keys
"noremap <Up> <NOP>
"noremap <Down> <NOP>
"noremap <Left> <NOP>
"noremap <Right> <NOP>
